FROM python:3.8-slim-buster

RUN apt-get update -y

# gcc compiler and opencv prerequisites
RUN apt-get -y install nano git build-essential libglib2.0-0 ffmpeg libsm6 libxext6 libxrender-dev


RUN apt-get install wget cmake libfreetype6-dev pkg-config libfontconfig-dev libjpeg-dev libopenjp2-7-dev -y
    
RUN pip install pyyaml==5.1 opencv-python pytesseract camelot-py img2pdf PyPDF2 pdf2image pandas poppler-utils

# Development packages
RUN pip install flask flask-cors requests opencv-python
RUN pip install cython
RUN pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

# Detectron2 prerequisites
RUN pip install torch==1.7.1+cpu torchvision==0.8.2+cpu -f https://download.pytorch.org/whl/torch_stable.html

# Detectron2 - CPU copy
RUN pip install -U 'git+https://github.com/facebookresearch/fvcore'
RUN python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'

# Create working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
RUN python -m githttps://github.com/nabeel3133/Table-Detection.git

# Copy contents
COPY . /usr/src/app

# Set environment variables
ENV HOME=/usr/src/app

RUN wget https://poppler.freedesktop.org/poppler-data-0.4.9.tar.gz \
    && tar -xf poppler-data-0.4.9.tar.gz \
    && cd poppler-data-0.4.9 \
    && make install \
    && cd .. \
    && wget https://poppler.freedesktop.org/poppler-20.08.0.tar.xz \
    && tar -xf poppler-20.08.0.tar.xz \
    && cd poppler-20.08.0 \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make \
    && make install \
    && ldconfig

